# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

# platform :android do
#   desc "Runs all the tests"
#   lane :test do
#     gradle(task: "test")
#   end
#
#   desc "Submit a new Beta Build to Crashlytics Beta"
#   lane :beta do
#     gradle(task: "clean assembleRelease")
#     crashlytics
#
#     # sh "your_script.sh"
#     # You can also use other beta testing services here
#   end
#
#   desc "Deploy a new version to the Google Play"
#   lane :deploy do
#     gradle(task: "clean assembleRelease")
#     upload_to_play_store
#   end
# end

platform :android do
 desc "Deploy to Firebase app distribution"
 lane :deploy do
  begin
#   build_android_app(task: "clean bundleRelease")
  build_android_app(task: "clean assembleRelease")
  firebase_app_distribution(
   app: "1:449844938614:android:79526f6a7cc20fc84d1c57",
   groups: "tester_group",
   release_notes: "Fastlane testing with jenkins",
#    android_artifact_path: "../build/app/outputs/bundle/release/app-release.aab ",
   android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
   firebase_cli_token: "1//0gRzkY7PndLikCgYIARAAGBASNwF-L9IrbDTx8DVLVGOGFH81o7HB2vDWwgIDYH-oZEO2sK6TSvFhPTGoNGc215eLIm9tRY4Gte0",
   android_artifact_type: "APK",
  )
  end
 end
end
